In [32]:
import pandas as pd
import requests

url = "https://priceline-com2.p.rapidapi.com/cars/search"

querystring = {
    "pickUpLocation": "BOM",
    "dropOffLocation": "BOM",
    "pickUpDate": "2024-12-26",
    "dropOffDate": "2024-12-27",
    "pickUpTime": "10:00",
    "dropOffTime": "10:00"
}

headers = {
    "x-rapidapi-key": "7f1bea6bb4msh78929f2c5e64eefp1988d4jsnece92c6405d1",
    "x-rapidapi-host": "priceline-com2.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)
data = response.json()

# Initialize an empty list to store vehicle data
vehicles_data = []

# Loop through the vehicles in the response
for vehicle in data.get('data', {}).get('vehicles', []):
    vehicle_info = {
        'Name': vehicle.get('name'),
        'Category': vehicle.get('categoryCodes', [None])[0],
        'Example': vehicle.get('example'),
        'Price': vehicle.get('rate', [{}])[0].get('totalPrice'),
        'Pickup Location': vehicle.get('pickupLocation', {}).get('line1'),
        'Return Location': vehicle.get('returnLocation', {}).get('line1'),
        'Fuel Type': vehicle.get('vehicleFeatures', {}).get('fuelType'),
        'AC': vehicle.get('vehicleFeatures', {}).get('isAC'),
        'Transmission': vehicle.get('vehicleFeatures', {}).get('transmission'),
        'People Capacity': vehicle.get('vehicleFeatures', {}).get('peopleCapacity'),
        'Image URL': vehicle.get('imageUrl')
    }
    vehicles_data.append(vehicle_info)

# Create DataFrame from the list of dictionaries
df = pd.DataFrame(vehicles_data)

# Display the DataFrame
print(df)

                       Name       Category  \
0               Compact Car        Compact
1               Premium Car        Premium
2               Economy Car        Economy
3                Luxury Car     Luxury Car
4  Standard-Size Diesel Van  Passenger Van
5         Standard-Size Car       Standard
6             Full-Size Van  Passenger Van
7              Mid-Size Car       Mid-Size

                                     Example  Price  \
0                             Honda City 1.5     99
1  Mercedes-benz Eclass Chauffeur Drive Only    350
2                           Maruti Dzire 1.2     72
3            Honda City Chauffeur Drive Only     67
4                   Toyota Innova 2.4 Crysta    125
5          Maruti Dzire Chauffeur Drive Only     44
6    Toyota Innova Crysta Chauffeur Drive On     70
7          Toyota Etios Chauffeur Drive Only     44

                         Pickup Location  \
0  Europcar, Chhatrapati Shivaji Maharaj
1          Airline Flight Dtls Mandatory
2  Europcar, Chhatrapati Shivaji Maharaj
3          Airline Flight Dtls Mandatory
4  Europcar, Chhatrapati Shivaji Maharaj
5          Airline Flight Dtls Mandatory
6          Airline Flight Dtls Mandatory
7          Airline Flight Dtls Mandatory

                         Return Location Fuel Type    AC Transmission  \
0  Europcar, Chhatrapati Shivaji Maharaj  Gasoline  True          man
1          Airline Flight Dtls Mandatory  Gasoline  True         auto
2  Europcar, Chhatrapati Shivaji Maharaj  Gasoline  True          man
3          Airline Flight Dtls Mandatory  Gasoline  True          man
4  Europcar, Chhatrapati Shivaji Maharaj    Diesel  True          man
5          Airline Flight Dtls Mandatory  Gasoline  True          man
6          Airline Flight Dtls Mandatory  Gasoline  True          man
7          Airline Flight Dtls Mandatory  Gasoline  True          man

   People Capacity                                          Image URL
0                4  https://s1.pclncdn.com/rc-static/v2/vehicles/p...
1                4  https://s1.pclncdn.com/rc-static/v2/vehicles/p...
2                4  https://s1.pclncdn.com/rc-static/v2/vehicles/p...
3                4  https://s1.pclncdn.com/rc-static/v2/vehicles/p...
4                7  https://s1.pclncdn.com/rc-static/v2/vehicles/p...
5                5  https://s1.pclncdn.com/rc-static/v2/vehicles/p...
6                6  https://s1.pclncdn.com/rc-static/v2/vehicles/p...
7                4  https://s1.pclncdn.com/rc-static/v2/vehicles/p...

In [33]:
df

,Name,Category,Example,Price,Pickup Location,Return Location,Fuel Type,AC,Transmission,People Capacity,Image URL
0,Compact Car,Compact,Honda City 1.5,99,"Europcar, Chhatrapati Shivaji Maharaj","Europcar, Chhatrapati Shivaji Maharaj",Gasoline,True,man,4,https://s1.pclncdn.com/rc-static/v2/vehicles/p...
1,Premium Car,Premium,Mercedes-benz Eclass Chauffeur Drive Only,350,Airline Flight Dtls Mandatory,Airline Flight Dtls Mandatory,Gasoline,True,auto,4,https://s1.pclncdn.com/rc-static/v2/vehicles/p...
2,Economy Car,Economy,Maruti Dzire 1.2,72,"Europcar, Chhatrapati Shivaji Maharaj","Europcar, Chhatrapati Shivaji Maharaj",Gasoline,True,man,4,https://s1.pclncdn.com/rc-static/v2/vehicles/p...
3,Luxury Car,Luxury Car,Honda City Chauffeur Drive Only,67,Airline Flight Dtls Mandatory,Airline Flight Dtls Mandatory,Gasoline,True,man,4,https://s1.pclncdn.com/rc-static/v2/vehicles/p...
4,Standard-Size Diesel Van,Passenger Van,Toyota Innova 2.4 Crysta,125,"Europcar, Chhatrapati Shivaji Maharaj","Europcar, Chhatrapati Shivaji Maharaj",Diesel,True,man,7,https://s1.pclncdn.com/rc-static/v2/vehicles/p...
5,Standard-Size Car,Standard,Maruti Dzire Chauffeur Drive Only,44,Airline Flight Dtls Mandatory,Airline Flight Dtls Mandatory,Gasoline,True,man,5,https://s1.pclncdn.com/rc-static/v2/vehicles/p...
6,Full-Size Van,Passenger Van,Toyota Innova Crysta Chauffeur Drive On,70,Airline Flight Dtls Mandatory,Airline Flight Dtls Mandatory,Gasoline,True,man,6,https://s1.pclncdn.com/rc-static/v2/vehicles/p...
7,Mid-Size Car,Mid-Size,Toyota Etios Chauffeur Drive Only,44,Airline Flight Dtls Mandatory,Airline Flight Dtls Mandatory,Gasoline,True,man,4,https://s1.pclncdn.com/rc-static/v2/vehicles/p...

In [34]:
df["Price"] = df["Price"] * 84

In [35]:
df2 = df[["Name","Price", "Category", "Example", "Pickup Location", "Return Location","People Capacity", "Image URL"]]

In [36]:
df2

,Name,Price,Category,Example,Pickup Location,Return Location,People Capacity,Image URL
0,Compact Car,8316,Compact,Honda City 1.5,"Europcar, Chhatrapati Shivaji Maharaj","Europcar, Chhatrapati Shivaji Maharaj",4,https://s1.pclncdn.com/rc-static/v2/vehicles/p...
1,Premium Car,29400,Premium,Mercedes-benz Eclass Chauffeur Drive Only,Airline Flight Dtls Mandatory,Airline Flight Dtls Mandatory,4,https://s1.pclncdn.com/rc-static/v2/vehicles/p...
2,Economy Car,6048,Economy,Maruti Dzire 1.2,"Europcar, Chhatrapati Shivaji Maharaj","Europcar, Chhatrapati Shivaji Maharaj",4,https://s1.pclncdn.com/rc-static/v2/vehicles/p...
3,Luxury Car,5628,Luxury Car,Honda City Chauffeur Drive Only,Airline Flight Dtls Mandatory,Airline Flight Dtls Mandatory,4,https://s1.pclncdn.com/rc-static/v2/vehicles/p...
4,Standard-Size Diesel Van,10500,Passenger Van,Toyota Innova 2.4 Crysta,"Europcar, Chhatrapati Shivaji Maharaj","Europcar, Chhatrapati Shivaji Maharaj",7,https://s1.pclncdn.com/rc-static/v2/vehicles/p...
5,Standard-Size Car,3696,Standard,Maruti Dzire Chauffeur Drive Only,Airline Flight Dtls Mandatory,Airline Flight Dtls Mandatory,5,https://s1.pclncdn.com/rc-static/v2/vehicles/p...
6,Full-Size Van,5880,Passenger Van,Toyota Innova Crysta Chauffeur Drive On,Airline Flight Dtls Mandatory,Airline Flight Dtls Mandatory,6,https://s1.pclncdn.com/rc-static/v2/vehicles/p...
7,Mid-Size Car,3696,Mid-Size,Toyota Etios Chauffeur Drive Only,Airline Flight Dtls Mandatory,Airline Flight Dtls Mandatory,4,https://s1.pclncdn.com/rc-static/v2/vehicles/p...

In [37]:
# Sort the DataFrame by 'Gross Price' in ascending order
df2 = df2.sort_values(by="Price", ascending=True)

# Reset the index if required
df2 = df2.reset_index(drop=True)
df2

,Name,Price,Category,Example,Pickup Location,Return Location,People Capacity,Image URL
0,Standard-Size Car,3696,Standard,Maruti Dzire Chauffeur Drive Only,Airline Flight Dtls Mandatory,Airline Flight Dtls Mandatory,5,https://s1.pclncdn.com/rc-static/v2/vehicles/p...
1,Mid-Size Car,3696,Mid-Size,Toyota Etios Chauffeur Drive Only,Airline Flight Dtls Mandatory,Airline Flight Dtls Mandatory,4,https://s1.pclncdn.com/rc-static/v2/vehicles/p...
2,Luxury Car,5628,Luxury Car,Honda City Chauffeur Drive Only,Airline Flight Dtls Mandatory,Airline Flight Dtls Mandatory,4,https://s1.pclncdn.com/rc-static/v2/vehicles/p...
3,Full-Size Van,5880,Passenger Van,Toyota Innova Crysta Chauffeur Drive On,Airline Flight Dtls Mandatory,Airline Flight Dtls Mandatory,6,https://s1.pclncdn.com/rc-static/v2/vehicles/p...
4,Economy Car,6048,Economy,Maruti Dzire 1.2,"Europcar, Chhatrapati Shivaji Maharaj","Europcar, Chhatrapati Shivaji Maharaj",4,https://s1.pclncdn.com/rc-static/v2/vehicles/p...
5,Compact Car,8316,Compact,Honda City 1.5,"Europcar, Chhatrapati Shivaji Maharaj","Europcar, Chhatrapati Shivaji Maharaj",4,https://s1.pclncdn.com/rc-static/v2/vehicles/p...
6,Standard-Size Diesel Van,10500,Passenger Van,Toyota Innova 2.4 Crysta,"Europcar, Chhatrapati Shivaji Maharaj","Europcar, Chhatrapati Shivaji Maharaj",7,https://s1.pclncdn.com/rc-static/v2/vehicles/p...
7,Premium Car,29400,Premium,Mercedes-benz Eclass Chauffeur Drive Only,Airline Flight Dtls Mandatory,Airline Flight Dtls Mandatory,4,https://s1.pclncdn.com/rc-static/v2/vehicles/p...

In [38]:

df2.to_csv('Cab.csv', index=False)

print("DataFrame has been successfully saved to 'Cab.csv'.")

DataFrame has been successfully saved to 'Cab.csv'.